name: Deploy Vite React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies & build
      run: |
        npm ci
        npm run build

    - name: Clean old frontend files
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          rm -rf /home/${{ secrets.SERVER_USER }}/public_html/*

    - name: Upload frontend build via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "./dist/*"
        target: "/home/${{ secrets.SERVER_USER }}/public_html/"

    - name: Move files out of dist to root
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          shopt -s dotglob
          mv /home/${{ secrets.SERVER_USER }}/public_html/dist/* /home/${{ secrets.SERVER_USER }}/public_html/
          rm -rf /home/${{ secrets.SERVER_USER }}/public_html/dist
          